version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./src
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/
        ports:
            - 8000:80
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
    db:
      container_name: db
      image: mysql
      restart: always
      command: --init-file /data/application/init.sql
      volumes:
        - ./init.sql:/data/application/init.sql
      environment:
          MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
          MYSQL_DATABASE: SCANDIWEB_TEST
          MYSQL_USER: MYSQL_USER
          MYSQL_PASSWORD: MYSQL_PASSWORD
      ports:
          - "9906:3306"